import { createHash } from 'node:crypto';
import { lstat, mkdir, open, readFile, readdir, realpath, rename, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');

const TYPES = new Map([
  ['.avif', 'image/avif'], ['.gif', 'image/gif'], ['.jpeg', 'image/jpeg'],
  ['.jpg', 'image/jpeg'], ['.mp4', 'video/mp4'], ['.png', 'image/png'],
  ['.webm', 'video/webm'], ['.webp', 'image/webp'],
]);
const MEDIA_URL = /\/(?:weekly-screenshots|slideshows|documents)\/([A-Za-z0-9._-]+)\/([A-Za-z0-9][A-Za-z0-9._/-]*)/g;
const OFFSET_TIME = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?[+-]\d{2}:\d{2}$/;
const SERVER_PREFIX = '// Generated by scripts/stage-scheduled-release.mjs. Do not edit.\nconst release = Object.freeze(';
const SERVER_SUFFIX = ');\n\nexport default release;\n';
const EDITION_INCLUDE = '{src/generated/scheduled-release/server.mjs,src/generated/scheduled-release/article.md}';
const MEDIA_INCLUDE = '{src/generated/scheduled-release/server.mjs,src/generated/scheduled-release/media/**}';

function fail(message) { throw new Error(`scheduled-release: ${message}`); }
export function digest(bytes) { return createHash('sha256').update(bytes).digest('hex'); }

function safeRelative(value, label) {
  if (typeof value !== 'string' || !value || value.includes('\\') || path.posix.isAbsolute(value)) fail(`${label} must be a safe relative path`);
  const normalized = path.posix.normalize(value);
  if (normalized !== value || normalized.split('/').some((part) => !part || part === '.' || part === '..')) fail(`${label} must be a safe relative path`);
  return normalized;
}

export function parseFrontmatter(raw) {
  const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
  if (!match) fail('article is missing frontmatter');
  const data = {};
  for (const line of match[1].split(/\r?\n/)) {
    const at = line.indexOf(':');
    if (at < 1) continue;
    let value = line.slice(at + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) value = value.slice(1, -1);
    data[line.slice(0, at).trim()] = value;
  }
  return { data, body: match[2] };
}

function slideshowFrom(manifest) {
  if (manifest.slideshow === undefined) {
    if (manifest.slideshowId !== undefined) fail('slideshow metadata and ordered slides are required when slideshowId is set');
    return null;
  }
  const show = manifest.slideshow;
  const id = show?.id ?? manifest.slideshowId;
  if (!show || typeof show !== 'object' || !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(id ?? '')) fail('slideshow is invalid');
  if (!show.title?.trim() || !show.description?.trim() || !Array.isArray(show.slides) || !show.slides.length) fail('slideshow title, description, and slides are required');
  const seen = new Set();
  const slides = show.slides.map((slide, index) => {
    if (!slide?.title?.trim()) fail(`slideshow slide ${index + 1} needs a title`);
    const mediaPath = safeRelative(slide.path, `slideshow slide ${index + 1}`);
    if (seen.has(mediaPath)) fail(`duplicate slideshow path: ${mediaPath}`);
    seen.add(mediaPath);
    return { title: slide.title, path: mediaPath };
  });
  return { id, title: show.title, description: show.description, slides };
}

function canonical(spec) {
  return JSON.stringify({
    schemaVersion: spec.schemaVersion, editionId: spec.editionId, publishAt: spec.publishAt,
    articleSha256: spec.article.sha256, slideshow: spec.slideshow,
    media: spec.media.map(({ path: name, sourceUrl, contentType, sha256 }) => ({ path: name, sourceUrl, contentType, sha256 })),
  });
}

function finalize(spec) { return { ...spec, releaseRevision: digest(canonical(spec)).slice(0, 24) }; }
function clientText(spec) {
  return `// Generated public locator metadata. Do not add private release fields.\nexport const scheduledEditionSlug = ${JSON.stringify(spec.editionId)};\nexport const scheduledEditionPublishAt = Date.parse(${JSON.stringify(spec.publishAt)});\n`;
}
function serverValue(spec) {
  return {
    schemaVersion: 1, editionId: spec.editionId, publishAt: spec.publishAt, publishAtMs: spec.publishAtMs,
    releaseRevision: spec.releaseRevision, source: spec.source,
    article: { file: 'article.md', sha256: spec.article.sha256 }, slideshow: spec.slideshow,
    media: Object.fromEntries(spec.media.map((item) => [item.path, {
      file: `media/${item.path}`, sourceUrl: item.sourceUrl, contentType: item.contentType, sha256: item.sha256,
    }])),
  };
}
function serverText(spec) { return `${SERVER_PREFIX}${JSON.stringify(serverValue(spec), null, 2)}${SERVER_SUFFIX}`; }

export function createScheduledReleaseTools({ root = repositoryRoot, now = Date.now } = {}) {
  const rootPath = path.resolve(root);
  const generatedDir = path.join(rootPath, 'src/generated/scheduled-release');
  const lockPath = path.join(rootPath, '.scheduled-release.lock');

  function rootRelative(file) { return path.relative(rootPath, file).split(path.sep).join('/'); }
  function resolveRoot(value, label) {
    const result = path.resolve(rootPath, safeRelative(value, label));
    if (!result.startsWith(`${rootPath}${path.sep}`)) fail(`${label} escapes the repository`);
    return result;
  }

  async function assertRoot() {
    const info = await lstat(rootPath);
    if (!info.isDirectory() || info.isSymbolicLink()) fail('repository root must be a real directory');
    return realpath(rootPath);
  }

  async function assertContainedPath(file, label, expectedKind) {
    const realRoot = await assertRoot();
    const relative = path.relative(rootPath, file);
    if (!relative || relative.startsWith('..') || path.isAbsolute(relative)) fail(`${label} escapes the repository`);
    let cursor = rootPath;
    for (const component of relative.split(path.sep)) {
      cursor = path.join(cursor, component);
      let info;
      try { info = await lstat(cursor); } catch (error) {
        if (error?.code === 'ENOENT') fail(`${label} does not exist: ${rootRelative(file)}`);
        throw error;
      }
      if (info.isSymbolicLink()) fail(`${label} contains a symlink: ${rootRelative(cursor)}`);
    }
    const actual = await realpath(file);
    if (!actual.startsWith(`${realRoot}${path.sep}`)) fail(`${label} resolves outside the repository`);
    const info = await lstat(file);
    if (expectedKind === 'file' && !info.isFile()) fail(`${label} must be a regular file`);
    if (expectedKind === 'directory' && !info.isDirectory()) fail(`${label} must be a directory`);
  }

  function publication(value, requireFuture) {
    if (typeof value !== 'string' || !OFFSET_TIME.test(value)) fail('publishAt must have an explicit numeric offset');
    const milliseconds = Date.parse(value);
    if (!Number.isFinite(milliseconds)) fail('publishAt is invalid');
    if (requireFuture && milliseconds <= now()) fail('publishAt must be in the future');
    return milliseconds;
  }

  async function specFromManifest(manifestName, { requireFuture = true } = {}) {
    const manifestFile = resolveRoot(manifestName, 'manifest');
    await assertContainedPath(manifestFile, 'manifest', 'file');
    let manifest;
    try { manifest = JSON.parse(await readFile(manifestFile, 'utf8')); } catch { fail('manifest is not valid JSON'); }
    if (manifest?.status !== 'scheduled') fail('manifest status must be scheduled');
    if (!/^edition-\d{4}-\d{2}-\d{2}-[a-z0-9-]+$/.test(manifest.editionId ?? '')) fail('editionId is invalid');
    const publishAtMs = publication(manifest.publishAt, requireFuture);
    const manifestRelative = rootRelative(manifestFile);
    const articleRelative = manifest.article ? safeRelative(manifest.article, 'article') : manifestRelative.replace(/\.release\.json$/, '.md');
    if (articleRelative === manifestRelative) fail('article must be declared or use a .release.json manifest name');
    const articleFile = resolveRoot(articleRelative, 'article');
    await assertContainedPath(articleFile, 'article', 'file');
    const articleBytes = await readFile(articleFile);
    const articleText = articleBytes.toString('utf8');
    const frontmatter = parseFrontmatter(articleText).data;
    if (frontmatter.id !== manifest.editionId) fail('article id does not match manifest');
    if (frontmatter.publishAt !== manifest.publishAt) fail('article publishAt does not match manifest');
    if (frontmatter.status !== 'scheduled') fail('article status must be scheduled');
    if (!/^\d{4}\.\d{2}\.\d{2}$/.test(manifest.assetFolder ?? '')) fail('assetFolder must use YYYY.MM.DD');
    const assetRootRelative = manifest.assetRoot ? safeRelative(manifest.assetRoot, 'assetRoot') : `src/articles/drafts/assets/${manifest.assetFolder}`;
    const assetRoot = resolveRoot(assetRootRelative, 'assetRoot');
    await assertContainedPath(assetRoot, 'assetRoot', 'directory');
    const slideshow = slideshowFrom(manifest);
    const selected = new Map();
    for (const match of articleText.matchAll(MEDIA_URL)) {
      if (match[1] !== manifest.assetFolder) fail(`article media uses the wrong dated folder: ${match[0]}`);
      const mediaPath = safeRelative(match[2], 'article media');
      selected.set(mediaPath, { path: mediaPath, sourceUrl: match[0] });
    }
    for (const slide of slideshow?.slides ?? []) if (!selected.has(slide.path)) selected.set(slide.path, { path: slide.path, sourceUrl: null });
    if (!selected.size) fail('release does not reference any media');
    const media = [];
    for (const item of [...selected.values()].sort((a, b) => a.path.localeCompare(b.path))) {
      const sourceFile = path.resolve(assetRoot, ...item.path.split('/'));
      if (!sourceFile.startsWith(`${assetRoot}${path.sep}`)) fail(`media escapes assetRoot: ${item.path}`);
      await assertContainedPath(sourceFile, `media ${item.path}`, 'file');
      const contentType = TYPES.get(path.extname(item.path).toLowerCase());
      if (!contentType) fail(`unsupported media extension: ${item.path}`);
      const bytes = await readFile(sourceFile);
      media.push({ ...item, sourceFile, contentType, sha256: digest(bytes), bytes });
    }
    return finalize({
      schemaVersion: 1, editionId: manifest.editionId, publishAt: manifest.publishAt, publishAtMs,
      source: { manifest: manifestRelative, article: articleRelative, assetRoot: assetRootRelative },
      article: { sourceFile: articleFile, sha256: digest(articleBytes), bytes: articleBytes }, slideshow, media,
    });
  }

  async function writePackage(directory, spec) {
    await mkdir(path.join(directory, 'media'), { recursive: true });
    await writeFile(path.join(directory, 'article.md'), spec.article.bytes);
    for (const item of spec.media) {
      const target = path.join(directory, 'media', ...item.path.split('/'));
      await mkdir(path.dirname(target), { recursive: true });
      await writeFile(target, item.bytes);
    }
    await writeFile(path.join(directory, 'server.mjs'), serverText(spec));
    await writeFile(path.join(directory, 'client.ts'), clientText(spec));
  }

  async function filesBelow(directory, prefix = '') {
    const files = [];
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      const name = prefix ? `${prefix}/${entry.name}` : entry.name;
      if (entry.isSymbolicLink()) fail(`generated package contains symlink: ${name}`);
      if (entry.isDirectory()) files.push(...await filesBelow(path.join(directory, entry.name), name));
      else if (entry.isFile()) files.push(name);
      else fail(`generated package contains non-regular entry: ${name}`);
    }
    return files.sort();
  }

  function parseServer(raw) {
    if (!raw.startsWith(SERVER_PREFIX) || !raw.endsWith(SERVER_SUFFIX)) fail('generated server config wrapper is malformed');
    try { return JSON.parse(raw.slice(SERVER_PREFIX.length, -SERVER_SUFFIX.length)); }
    catch { fail('generated server config JSON is malformed'); }
  }

  function publicMediaTargets(spec) {
    return spec.media.map((item) => {
      if (item.sourceUrl) return { item, file: path.join(rootPath, 'public', ...item.sourceUrl.slice(1).split('/')) };
      if (!spec.slideshow) fail(`media has no approved public target: ${item.path}`);
      const date = path.posix.basename(spec.source.assetRoot);
      const slideName = item.path.startsWith('slideshow/') ? item.path.slice('slideshow/'.length) : item.path;
      return { item, file: path.join(rootPath, 'public/slideshows', date, spec.slideshow.id, ...slideName.split('/')) };
    });
  }

  async function scanStaticLeaks(spec) {
    const articleText = spec.article.bytes.toString('utf8');
    const { data: frontmatter, body } = parseFrontmatter(articleText);
    const publicSourceText = [];
    const articleIndex = await readFile(path.join(rootPath, 'src/articles/index.ts'), 'utf8');
    for (const found of articleIndex.matchAll(/from ['"](\.\/[^'"]+\.md)\?raw['"]/g)) {
      const publishedFile = path.resolve(rootPath, 'src/articles', found[1]);
      await assertContainedPath(publishedFile, 'published article', 'file');
      const published = parseFrontmatter(await readFile(publishedFile, 'utf8'));
      const publishedAt = published.data.publishAt
        ? publication(published.data.publishAt, false)
        : Date.parse(`${published.data.date}T00:00:00Z`);
      if (!Number.isFinite(publishedAt) || publishedAt > now()) continue;
      publicSourceText.push(published.body);
    }
    async function collectPublicClientSource(directory) {
      for (const entry of await readdir(directory, { withFileTypes: true })) {
        const file = path.join(directory, entry.name);
        const relative = rootRelative(file);
        if (entry.isSymbolicLink()) fail(`public client source contains a symlink: ${relative}`);
        if (entry.isDirectory()) {
          if (relative === 'src/articles/drafts' || relative === 'src/generated') continue;
          await collectPublicClientSource(file);
        } else if (entry.isFile() && /\.(?:[cm]?[jt]sx?|svelte|json)$/.test(entry.name)) {
          publicSourceText.push(await readFile(file, 'utf8'));
        }
      }
    }
    await collectPublicClientSource(path.join(rootPath, 'src'));
    const forbiddenText = new Map();
    const addText = (label, value, minimum = 1) => {
      if (typeof value !== 'string' || value.length < minimum) return;
      forbiddenText.set(value, label);
      const escaped = JSON.stringify(value).slice(1, -1);
      if (escaped !== value) forbiddenText.set(escaped, `${label} (escaped)`);
    };
    addText('article title', frontmatter.title, 8);
    addText('article summary', frontmatter.summary, 12);
    for (const line of body.split(/\r?\n/).map((value) => value.trim()).filter((value) => value.length >= 32)) {
      // Text already present in public client source or a registered, published
      // edition is not evidence that the active private article entered a bundle.
      // Unique private lines, identity fields, paths, hashes, and media bytes
      // remain forbidden.
      if (!publicSourceText.some((source) => source.includes(line))) addText('article body marker', line);
    }
    for (const sourcePath of [spec.source.manifest, spec.source.article, spec.source.assetRoot, 'src/generated/scheduled-release']) {
      addText('private source path', sourcePath);
    }
    addText('article hash', spec.article.sha256);
    addText('release revision', spec.releaseRevision);

    const protectedHashes = new Map([[spec.article.sha256, 'article.md']]);
    const rawMedia = [];
    const base64Media = [];
    const candidates = new Set(publicMediaTargets(spec).map(({ file }) => file));
    for (const item of spec.media) {
      protectedHashes.set(item.sha256, item.path);
      addText(`media hash ${item.path}`, item.sha256);
      addText(`private media path ${item.path}`, `media/${item.path}`);
      if (item.sourceUrl) addText(`media URL ${item.path}`, item.sourceUrl);
      const basename = path.posix.basename(item.path);
      if (!/^slide-\d+\.[a-z0-9]+$/i.test(basename)) addText(`media filename ${item.path}`, basename, 8);
      if (!item.sourceUrl && spec.slideshow) {
        const date = path.posix.basename(spec.source.assetRoot);
        const slideName = item.path.startsWith('slideshow/') ? item.path.slice('slideshow/'.length) : item.path;
        const publicUrl = `/slideshows/${date}/${spec.slideshow.id}/${slideName}`;
        addText(`media URL ${item.path}`, publicUrl);
      }
      const rawProbeStart = Math.max(0, Math.floor(item.bytes.length / 2) - 32);
      rawMedia.push({ label: item.path, bytes: item.bytes, probe: item.bytes.subarray(rawProbeStart, rawProbeStart + 64) });
      const base64 = item.bytes.toString('base64');
      const base64ProbeStart = Math.max(0, Math.floor(base64.length / 2) - 32);
      base64Media.push({ label: item.path, value: base64, probe: base64.slice(base64ProbeStart, base64ProbeStart + 64) });
    }

    async function collect(directory) {
      let entries;
      try { entries = await readdir(directory, { withFileTypes: true }); } catch (error) { if (error?.code === 'ENOENT') return; throw error; }
      for (const entry of entries) {
        const file = path.join(directory, entry.name);
        if (entry.isSymbolicLink()) fail(`static tree contains a symlink: ${rootRelative(file)}`);
        if (entry.isDirectory()) await collect(file);
        else if (entry.isFile()) candidates.add(file);
      }
    }
    await collect(path.join(rootPath, 'public'));
    await collect(path.join(rootPath, 'dist'));
    for (const file of [...candidates].sort()) {
      let info;
      try { info = await lstat(file); } catch (error) { if (error?.code === 'ENOENT') continue; throw error; }
      if (info.isSymbolicLink()) fail(`static candidate is a symlink: ${rootRelative(file)}`);
      if (!info.isFile()) continue;
      const bytes = await readFile(file);
      const exact = protectedHashes.get(digest(bytes));
      if (exact) fail(`active private release has a static duplicate of ${exact}: ${rootRelative(file)}`);
      const text = bytes.toString('utf8');
      for (const [needle, label] of forbiddenText) {
        if (text.includes(needle)) fail(`active private release leaks ${label}: ${rootRelative(file)}`);
      }
      for (const media of rawMedia) {
        if (bytes.length >= media.bytes.length && bytes.includes(media.probe) && bytes.includes(media.bytes)) {
          fail(`active private release embeds raw media ${media.label}: ${rootRelative(file)}`);
        }
      }
      for (const media of base64Media) {
        if (text.length >= media.value.length && text.includes(media.probe) && text.includes(media.value)) {
          fail(`active private release embeds base64 media ${media.label}: ${rootRelative(file)}`);
        }
      }
    }
  }

  function expandIncludePattern(value) {
    const match = value.match(/^(.*)\{([^{}]+)\}(.*)$/);
    if (!match) return [value];
    return match[2].split(',').flatMap((part) => expandIncludePattern(`${match[1]}${part}${match[3]}`));
  }

  function globExpression(pattern) {
    let expression = '^';
    for (let index = 0; index < pattern.length; index += 1) {
      const character = pattern[index];
      if (character === '*' && pattern[index + 1] === '*') { expression += '.*'; index += 1; }
      else if (character === '*') expression += '[^/]*';
      else expression += character.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    }
    return new RegExp(`${expression}$`);
  }

  async function verifyFunctionInventory(approvedSpec) {
    let spec = approvedSpec;
    if (!spec) {
      const rawServer = await readFile(path.join(generatedDir, 'server.mjs'), 'utf8');
      const active = parseServer(rawServer);
      if (typeof active.source?.manifest !== 'string') fail('generated config source manifest is invalid');
      spec = await specFromManifest(active.source.manifest, { requireFuture: false });
      if (rawServer !== serverText(spec)) fail('generated server config differs from approved sources');
    }
    const config = JSON.parse(await readFile(path.join(rootPath, 'vercel.json'), 'utf8'));
    const configured = {
      'api/scheduled-edition.mjs': config.functions?.['api/scheduled-edition.mjs']?.includeFiles,
      'api/scheduled-media.mjs': config.functions?.['api/scheduled-media.mjs']?.includeFiles,
    };
    if (configured['api/scheduled-edition.mjs'] !== EDITION_INCLUDE) fail('scheduled edition function includeFiles inventory is not exact');
    if (configured['api/scheduled-media.mjs'] !== MEDIA_INCLUDE) fail('scheduled media function includeFiles inventory is not exact');
    const generatedFiles = (await filesBelow(generatedDir)).map((name) => `src/generated/scheduled-release/${name}`);
    const resolved = {};
    for (const [functionName, includeValue] of Object.entries(configured)) {
      const expressions = expandIncludePattern(includeValue).map(globExpression);
      resolved[functionName] = generatedFiles.filter((name) => expressions.some((expression) => expression.test(name))).sort();
    }
    const expected = {
      'api/scheduled-edition.mjs': ['src/generated/scheduled-release/article.md', 'src/generated/scheduled-release/server.mjs'],
      'api/scheduled-media.mjs': ['src/generated/scheduled-release/server.mjs', ...spec.media.map((item) => `src/generated/scheduled-release/media/${item.path}`)].sort(),
    };
    for (const functionName of Object.keys(expected)) {
      if (JSON.stringify(resolved[functionName]) !== JSON.stringify(expected[functionName])) {
        fail(`${functionName} resolved includeFiles has missing, extra, or unapproved files`);
      }
    }
    return resolved;
  }

  async function verifyInternalPackage() {
    let info;
    try { info = await lstat(generatedDir); } catch (error) { if (error?.code === 'ENOENT') fail('generated release package is missing'); throw error; }
    if (!info.isDirectory() || info.isSymbolicLink()) fail('generated release package must be a real directory');
    const rawServer = await readFile(path.join(generatedDir, 'server.mjs'), 'utf8');
    const config = parseServer(rawServer);
    if (config?.schemaVersion !== 1 || typeof config.source?.manifest !== 'string' || typeof config.source?.article !== 'string' || typeof config.source?.assetRoot !== 'string') {
      fail('generated config schema or source paths are invalid');
    }
    safeRelative(config.source.manifest, 'generated source manifest');
    safeRelative(config.source.article, 'generated source article');
    safeRelative(config.source.assetRoot, 'generated source assetRoot');
    if (!/^edition-\d{4}-\d{2}-\d{2}-[a-z0-9-]+$/.test(config.editionId ?? '')) fail('generated editionId is invalid');
    const publishAtMs = publication(config.publishAt, false);
    if (config.publishAtMs !== publishAtMs) fail('generated publishAtMs is invalid');
    if (config.article?.file !== 'article.md' || !/^[a-f0-9]{64}$/.test(config.article.sha256 ?? '')) fail('generated article config is invalid');
    const articleBytes = await readFile(path.join(generatedDir, 'article.md'));
    if (digest(articleBytes) !== config.article.sha256) fail('generated article hash mismatch');
    const articleText = articleBytes.toString('utf8');
    const articleData = parseFrontmatter(articleText).data;
    if (articleData.id !== config.editionId || articleData.publishAt !== config.publishAt || articleData.status !== 'scheduled') fail('generated article identity is invalid');
    const slideshow = config.slideshow === null ? null : slideshowFrom({ slideshow: config.slideshow });
    const referenced = new Map();
    const assetDate = path.posix.basename(config.source.assetRoot);
    for (const match of articleText.matchAll(MEDIA_URL)) {
      if (match[1] !== assetDate) fail(`generated article media uses wrong dated folder: ${match[0]}`);
      referenced.set(safeRelative(match[2], 'generated article media'), match[0]);
    }
    for (const slide of slideshow?.slides ?? []) if (!referenced.has(slide.path)) referenced.set(slide.path, null);
    const configuredNames = Object.keys(config.media ?? {}).sort();
    if (JSON.stringify(configuredNames) !== JSON.stringify([...referenced.keys()].sort())) fail('generated media allowlist does not match article and slideshow references');
    const media = [];
    for (const name of configuredNames) {
      safeRelative(name, 'generated media path');
      const item = config.media[name];
      const contentType = TYPES.get(path.extname(name).toLowerCase());
      if (!item || item.file !== `media/${name}` || item.contentType !== contentType || item.sourceUrl !== referenced.get(name) || !/^[a-f0-9]{64}$/.test(item.sha256 ?? '')) {
        fail(`generated media config is invalid: ${name}`);
      }
      const bytes = await readFile(path.join(generatedDir, item.file));
      if (digest(bytes) !== item.sha256) fail(`generated media hash mismatch: ${name}`);
      media.push({ path: name, sourceUrl: item.sourceUrl, sourceFile: null, contentType, sha256: item.sha256, bytes });
    }
    const spec = finalize({
      schemaVersion: 1, editionId: config.editionId, publishAt: config.publishAt, publishAtMs,
      source: { manifest: config.source.manifest, article: config.source.article, assetRoot: config.source.assetRoot },
      article: { sourceFile: null, sha256: config.article.sha256, bytes: articleBytes }, slideshow, media,
    });
    if (config.releaseRevision !== spec.releaseRevision || rawServer !== serverText(spec)) fail('generated server config is not internally canonical');
    if (await readFile(path.join(generatedDir, 'client.ts'), 'utf8') !== clientText(spec)) fail('generated client config is not internally canonical');
    const expected = ['article.md', 'client.ts', 'server.mjs', ...media.map(({ path: name }) => `media/${name}`)].sort();
    if (JSON.stringify(await filesBelow(generatedDir)) !== JSON.stringify(expected)) fail('generated package has unexpected or missing files');
    await verifyFunctionInventory(spec);
    return { config: serverValue(spec), spec, rawServer };
  }

  async function verifyGeneratedRelease({ checkStaticDuplicates = true } = {}) {
    const internal = await verifyInternalPackage();
    const approved = await specFromManifest(internal.config.source.manifest, { requireFuture: false });
    if (internal.rawServer !== serverText(approved)) fail('generated server config differs from approved sources');
    if (await readFile(path.join(generatedDir, 'client.ts'), 'utf8') !== clientText(approved)) fail('generated client config differs from approved sources');
    if (checkStaticDuplicates) await scanStaticLeaks(approved);
    return serverValue(approved);
  }

  async function activeRelease() {
    let info;
    try { info = await lstat(generatedDir); } catch (error) { if (error?.code === 'ENOENT') return null; throw error; }
    if (!info.isDirectory() || info.isSymbolicLink()) fail('active generated release is invalid');
    return verifyInternalPackage();
  }

  async function isPromoted(active, activeSpec) {
    const index = await readFile(path.join(rootPath, 'src/articles/index.ts'), 'utf8');
    let matches = 0;
    for (const found of index.matchAll(/from ['"](\.\/[^'"]+\.md)\?raw['"]/g)) {
      try {
        const article = path.resolve(rootPath, 'src/articles', found[1]);
        await assertContainedPath(article, 'promoted article', 'file');
        if (parseFrontmatter(await readFile(article, 'utf8')).data.id === active.editionId) matches += 1;
      } catch { /* malformed static imports fail the normal content/build checks */ }
    }
    if (matches !== 1) return false;
    if (active.slideshow) {
      const registry = await readFile(path.join(rootPath, 'src/articles/slideshows.ts'), 'utf8');
      const id = active.slideshow.id.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      if ((registry.match(new RegExp(`['"]${id}['"]\\s*:`, 'g')) ?? []).length !== 1) return false;
    }
    for (const { item, file } of publicMediaTargets(activeSpec)) {
      try {
        await assertContainedPath(file, `promoted media ${item.path}`, 'file');
        if (digest(await readFile(file)) !== item.sha256) return false;
      } catch {
        return false;
      }
    }
    return true;
  }

  async function acquireLock() {
    let handle;
    try { handle = await open(lockPath, 'wx'); } catch (error) { if (error?.code === 'EEXIST') fail('another staging process is running'); throw error; }
    return async () => { await handle.close(); await rm(lockPath, { force: true }); };
  }

  async function stageRelease(manifest) {
    const unlock = await acquireLock();
    const parent = path.dirname(generatedDir);
    const next = path.join(parent, `.scheduled-release.next-${process.pid}`);
    const previous = path.join(parent, `.scheduled-release.previous-${process.pid}`);
    let backedUp = false;
    try {
      const spec = await specFromManifest(manifest, { requireFuture: true });
      const active = await activeRelease();
      if (active && active.config.editionId !== spec.editionId) {
        const approvedActive = await verifyGeneratedRelease({ checkStaticDuplicates: false });
        const approvedActiveSpec = await specFromManifest(approvedActive.source.manifest, { requireFuture: false });
        if (now() < approvedActive.publishAtMs) fail(`active edition ${approvedActive.editionId} has not reached publishAt`);
        if (!(await isPromoted(approvedActive, approvedActiveSpec))) fail(`active edition ${approvedActive.editionId} is not fully promoted with approved public media`);
      }
      await rm(next, { recursive: true, force: true });
      await writePackage(next, spec);
      const original = generatedDir;
      // Verify candidate bytes without weakening active-package handling.
      await verifyCandidate(next, spec);
      await mkdir(parent, { recursive: true });
      try { await rename(original, previous); backedUp = true; } catch (error) { if (error?.code !== 'ENOENT') throw error; }
      try { await rename(next, original); } catch (error) { if (backedUp) { await rename(previous, original); backedUp = false; } throw error; }
      await rm(previous, { recursive: true, force: true });
      backedUp = false;
      return serverValue(spec);
    } finally {
      await rm(next, { recursive: true, force: true });
      // Preserve a backup if rollback itself failed.
      await unlock();
    }
  }

  async function verifyCandidate(directory, spec) {
    if (await readFile(path.join(directory, 'server.mjs'), 'utf8') !== serverText(spec)) fail('candidate server config is stale');
    if (await readFile(path.join(directory, 'client.ts'), 'utf8') !== clientText(spec)) fail('candidate client config is stale');
    const expected = ['article.md', 'client.ts', 'server.mjs', ...spec.media.map(({ path: name }) => `media/${name}`)].sort();
    if (JSON.stringify(await filesBelow(directory)) !== JSON.stringify(expected)) fail('candidate package inventory is invalid');
  }

  return { root: rootPath, generatedDir, specFromManifest, stageRelease, verifyGeneratedRelease, verifyFunctionInventory };
}

const production = createScheduledReleaseTools();
export const generatedReleaseDir = production.generatedDir;
export const specFromManifest = production.specFromManifest;
export const stageRelease = production.stageRelease;
export const verifyGeneratedRelease = production.verifyGeneratedRelease;
export const verifyFunctionInventory = production.verifyFunctionInventory;
